name: CD

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: uhdre-gamdi-api
  AWS_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build-image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ env.DATABASE_URL }} \
            -t uhdre-gamdi-api \
            .
      - name: Tag Docker iamge
        id: tag-image
        run: docker tag uhdre-gamdi-api:latest 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/uhdre-gamdi-api:latest

      - name: Push Docker image to Amazon ECR
        id: push-image
        run: docker push 078512149071.dkr.ecr.ap-northeast-2.amazonaws.com/uhdre-gamdi-api:latest
